  spring:
    datasource:
      driver-class-name: org.postgresql.Driver
      url: jdbc:postgresql://localhost5432/test_spring_db
      username: test-user
      password: "123456"
    jpa:
      properties:
        hibernate:
          dialect: org.hibernate.dialect.PostgreSQL10Dialect
          show_sql: true
          temp:
            use_jdbc_metadata_defaults: false